"""
Relicon AI Ad Creator - Database Models
SQLAlchemy ORM models for data persistence
"""
import uuid
from datetime import datetime
from typing import Dict, Any
from sqlalchemy import (
    Column, String, Integer, Float, Boolean, DateTime, Text, JSON,
    Enum as SQLEnum, UniqueConstraint, Index, ForeignKey
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship

from .connection import Base
from ..models.enums import JobStatus, AdPlatform, AdStyle


class AdJob(Base):
    """
    Main ad creation job tracking
    
    Stores comprehensive information about each ad creation request,
    including progress tracking, results, and error handling.
    """
    __tablename__ = "ad_jobs"
    
    # Primary Fields
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    job_id = Column(String(50), unique=True, nullable=False, index=True)
    status = Column(SQLEnum(JobStatus), default=JobStatus.PENDING, nullable=False, index=True)
    
    # Business Information
    brand_name = Column(String(100), nullable=False, index=True)
    brand_description = Column(Text, nullable=False)
    product_name = Column(String(100))
    target_audience = Column(Text)
    unique_selling_point = Column(Text)
    call_to_action = Column(String(100))
    
    # Technical Specifications
    duration = Column(Integer, default=30)
    platform = Column(SQLEnum(AdPlatform), default=AdPlatform.UNIVERSAL)
    style = Column(SQLEnum(AdStyle), default=AdStyle.PROFESSIONAL)
    
    # Progress Tracking
    progress_percentage = Column(Integer, default=0)
    current_step = Column(String(100))
    message = Column(Text)
    
    # Results and Data
    video_url = Column(String(500))
    master_plan = Column(JSON)
    generation_stats = Column(JSON)
    error_details = Column(Text)
    
    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    completed_at = Column(DateTime)
    
    # Relationships
    uploaded_assets = relationship("UploadedAsset", back_populates="job")
    generated_assets = relationship("GeneratedAsset", back_populates="job")
    analytics = relationship("AdAnalytics", back_populates="job", uselist=False)
    
    # Constraints and Indexes
    __table_args__ = (
        UniqueConstraint('job_id', name='uq_ad_jobs_job_id'),
        Index('ix_ad_jobs_status_created', 'status', 'created_at'),
        Index('ix_ad_jobs_brand_platform', 'brand_name', 'platform'),
    )
    
    def __repr__(self):
        return f"<AdJob(job_id='{self.job_id}', brand='{self.brand_name}', status='{self.status}')>"
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert job to dictionary for API responses"""
        return {
            'job_id': self.job_id,
            'status': self.status.value,
            'brand_name': self.brand_name,
            'progress_percentage': self.progress_percentage,
            'current_step': self.current_step,
            'message': self.message,
            'video_url': self.video_url,
            'created_at': self.created_at.isoformat() if self.created_at else None,
            'updated_at': self.updated_at.isoformat() if self.updated_at else None,
            'completed_at': self.completed_at.isoformat() if self.completed_at else None,
        }


class UploadedAsset(Base):
    """
    User-uploaded assets for ad customization
    
    Tracks files uploaded by users (logos, images, videos, audio)
    for inclusion in their ads.
    """
    __tablename__ = "uploaded_assets"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    job_id = Column(String(50), ForeignKey('ad_jobs.job_id'), nullable=False, index=True)
    
    # File Information
    filename = Column(String(255), nullable=False)
    original_filename = Column(String(255), nullable=False)
    file_type = Column(String(50), nullable=False)
    file_size = Column(Integer, nullable=False)
    file_path = Column(String(500), nullable=False)
    
    # Metadata and Processing
    file_metadata = Column(JSON)
    processing_status = Column(String(50), default="uploaded")
    processing_notes = Column(Text)
    
    # Timestamps
    uploaded_at = Column(DateTime, default=datetime.utcnow)
    processed_at = Column(DateTime)
    
    # Relationships
    job = relationship("AdJob", back_populates="uploaded_assets")
    
    # Constraints
    __table_args__ = (
        Index('ix_uploaded_assets_job_type', 'job_id', 'file_type'),
    )
    
    def __repr__(self):
        return f"<UploadedAsset(filename='{self.filename}', job_id='{self.job_id}')>"


class GeneratedAsset(Base):
    """
    AI-generated assets during ad creation
    
    Tracks all assets generated by AI services (Luma videos,
    ElevenLabs audio, etc.) with generation metadata.
    """
    __tablename__ = "generated_assets"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    job_id = Column(String(50), ForeignKey('ad_jobs.job_id'), nullable=False, index=True)
    
    # Asset Information
    asset_type = Column(String(50), nullable=False, index=True)  # video, audio, image
    asset_purpose = Column(String(100))  # scene_1_video, voiceover, background_music
    file_path = Column(String(500), nullable=False)
    file_size = Column(Integer)
    
    # Generation Details
    generation_prompt = Column(Text)
    generation_parameters = Column(JSON)
    generation_service = Column(String(50))  # luma, elevenlabs, openai
    
    # Quality and Performance Metrics
    quality_score = Column(Float)
    generation_time_seconds = Column(Float)
    service_cost = Column(Float)
    
    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow)
    
    # Relationships
    job = relationship("AdJob", back_populates="generated_assets")
    
    # Constraints
    __table_args__ = (
        Index('ix_generated_assets_job_type', 'job_id', 'asset_type'),
        Index('ix_generated_assets_service', 'generation_service', 'created_at'),
    )
    
    def __repr__(self):
        return f"<GeneratedAsset(type='{self.asset_type}', service='{self.generation_service}')>"


class AdAnalytics(Base):
    """
    Analytics and performance tracking for ad creation
    
    Stores detailed metrics about the ad creation process,
    including timing, costs, and quality scores.
    """
    __tablename__ = "ad_analytics"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    job_id = Column(String(50), ForeignKey('ad_jobs.job_id'), nullable=False, unique=True, index=True)
    
    # Performance Timing (seconds)
    total_generation_time = Column(Float)
    planning_time = Column(Float)
    script_generation_time = Column(Float)
    audio_generation_time = Column(Float)
    video_generation_time = Column(Float)
    assembly_time = Column(Float)
    
    # Quality Scores (0.0 to 1.0)
    overall_quality_score = Column(Float)
    script_quality_score = Column(Float)
    audio_quality_score = Column(Float)
    video_quality_score = Column(Float)
    
    # Resource Usage
    cpu_usage_percent = Column(Float)
    memory_usage_mb = Column(Float)
    gpu_usage_percent = Column(Float)
    
    # Cost Tracking (USD)
    openai_cost = Column(Float, default=0.0)
    luma_cost = Column(Float, default=0.0)
    elevenlabs_cost = Column(Float, default=0.0)
    total_cost = Column(Float, default=0.0)
    
    # User Feedback
    user_rating = Column(Integer)  # 1-5 stars
    user_feedback = Column(Text)
    
    # Additional Metrics
    retry_count = Column(Integer, default=0)
    error_count = Column(Integer, default=0)
    
    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow)
    
    # Relationships
    job = relationship("AdJob", back_populates="analytics")
    
    def __repr__(self):
        return f"<AdAnalytics(job_id='{self.job_id}', total_time={self.total_generation_time})>"


class SystemMetrics(Base):
    """
    Overall system performance and health metrics
    
    Tracks system-wide performance, health status, and
    operational metrics for monitoring and scaling.
    """
    __tablename__ = "system_metrics"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    
    # Timestamp
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
    
    # System Statistics
    active_jobs = Column(Integer, default=0)
    queue_size = Column(Integer, default=0)
    total_jobs_processed = Column(Integer, default=0)
    success_rate = Column(Float, default=0.0)
    
    # Performance Metrics
    average_generation_time = Column(Float)
    system_uptime_seconds = Column(Integer)
    
    # Resource Usage
    cpu_usage = Column(Float)
    memory_usage = Column(Float)
    disk_usage = Column(Float)
    
    # Service Health Status
    database_healthy = Column(Boolean, default=True)
    redis_healthy = Column(Boolean, default=True)
    openai_healthy = Column(Boolean, default=True)
    luma_healthy = Column(Boolean, default=True)
    elevenlabs_healthy = Column(Boolean, default=True)
    
    # Error Tracking
    error_count_last_hour = Column(Integer, default=0)
    warning_count_last_hour = Column(Integer, default=0)
    
    # Constraints
    __table_args__ = (
        Index('ix_system_metrics_timestamp', 'timestamp'),
    )
    
    def __repr__(self):
        return f"<SystemMetrics(timestamp='{self.timestamp}', active_jobs={self.active_jobs})>" 